import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoryblokProvider from "@/components/StoryblokProvider";
// import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
// import { Page } from "@/components/Page";
// import { Grid } from "@/components/Grid";
// import { Hero } from "@/components/Hero";
// import { Feature } from "@/components/Feature";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// storyblokInit({
//   accessToken: process.env.STORYBLOK_DELIVERY_API_TOKEN,
//   use: [apiPlugin],
//   components: {
//     page: Page,
//     grid: Grid,
//     hero: Hero,
//     feature: Feature,
//   },
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>Layout Head</div>
        {children}
      </body>
    </html>
    </StoryblokProvider>
  );
}
